{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.omakix;
in {
  config = lib.mkIf cfg.enable {
    programs.bash = {
      enable = true;
      historyControl = ["ignoredups" "ignorespace"];
      historySize = 32768;
      historyFileSize = 32768;
      shellAliases = {
        # File system
        ls = "eza -lh --group-directories-first";
        lsa = "ls -a";
        lt = "eza --tree --level=2 --long --icons --git";
        lta = "lt -a";
        ff = "fzf --preview 'batcat --style=numbers --color=always {}'";

        # Directories
        ".." = "cd ..";
        "..." = "cd ../..";
        "...." = "cd ../../..";

        # Tools
        n = "nvim";
        g = "git";
        d = "docker";
        r = "rails";
        bat = "batcat";
        lzg = "lazygit";
        lzd = "lazydocker";

        # Git
        gcm = "git commit -m";
        gcam = "git commit -a -m";
        gcad = "git commit -a --amend";

        # Compression
        decompress = "tar -xzf";
      };

      initExtra = ''
        # Compression
        compress() { tar -czf "''${1%/}.tar.gz" "''${1%/}"; }

        # Convert webm files generated by the Gnome screenshot video recorder to mp4s that are more compatible
        webm2mp4() {
          input_file="$1"
          output_file="''${input_file%.webm}.mp4"
          ffmpeg -i "$input_file" -c:v libx264 -preset slow -crf 22 -c:a aac -b:a 192k "$output_file"
        }

        force_color_prompt=yes
        color_prompt=yes

        PS1=$'\uf0a9 '
        PS1="\[\e]0;\w\a\]$PS1"
      '';
    };
  };
}
